name: Test Meteor Package
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        meteorRelease:
          - '--release 2.3.2'
          - '--release 2.4.1'
          - '--release 2.5.6'
          - '--release 2.6.1'
          - '--release 2.7.3'
          - '--release 2.8.2'
          - '--release 2.9.0'
          - '--release 2.10.0'
          - '--release 2.11.0'
          - '--release 2.12'
          - '--release 2.13.2'
          - '--release 2.14'
          - '--release 2.15'
          - '--release 2.16'
          - '--release 3.0.3'
          # Latest version
          -
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest
          npm install

      - name: Run Tests
        run: |
          # Fix using old versions of Meteor
          export NODE_TLS_REJECT_UNAUTHORIZED=0
          mtest --package ./ --once ${{ matrix.meteorRelease }} 
